import type { Metadata } from "next";
import {  DM_Serif_Display, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import CursorDot from "@/components/CursorDot";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const dmSerifDisplay = DM_Serif_Display({
  variable: "--font-dm-serif",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", inter.variable, dmSerifDisplay.variable, "font-sans")}
    >
      <body className="min-h-full flex flex-col"suppressHydrationWarning>
        <CursorDot/>
        {children}
      </body>
    </html>
  );
}
