name: millennial

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  # PRE BUILD:  Test Build before build inside actual machine
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Setup Node JS
        uses: actions/setup-node@v6
        with:
          node-version: "24.16.0"
      - name: Install Dependencies
        run: npm install  --frozen-lockfile
      - name: Build Now
        run: npm run build
  # BUILD: Now Connect with SSH AND Build inside machain
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
      - name: Setup Node JS
        uses: actions/setup-node@v6
        with:
          node-version: "24.16.0"
      - name: Install Dependencies
        run: npm ci
      - name: Build the Code
        run: npm run build
      - name: COPY FILE VIA SCP
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/${{secrets.EC2_USER }}/${{ secrets.PROJECT_FOLDER }}"
          rm: false
          strip_components: 0

      - name: Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_FOLDER }}

            echo '${{ secrets.ENV_FILE }}' > .env

            npm install 
            npm run build
            pm2 restart ecosystem.config.cjs --update-env